# -*- coding: utf-8 -*-
"""Spider_ML_TASK2_BASE_ML_Level2_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ySaFm6aPOFF0Jp-iLwXDjowsP8B4koH

# SPIDER ML Task 2_Base ML Level 2
## Custom LSTM for Weather Forecasting

In this notebook, I will build a custom LSTM from scratch for weather forecasting.The model will use previous weather observations to predict future temperature values.

## Problem Statement

The goal is to build a custom LSTM manually without using any built-in recurrent layer.We will use the Jena Climate dataset, prepare hourly data, create sequence windows, train the model,and evaluate predictions.
"""

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import mean_absolute_error, mean_squared_error

"""## Setup

We first check the device and set basic parameters for training
"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""## Load Dataset

We load the Jena Climate dataset and prepare it for hourly forecasting.
The original data is recorded every 10 minutes, so we will downsample it by averaging every 6 rows
"""

df = pd.read_csv("jena_climate_2009_2016.csv.zip")
df.head()

print(df.columns)
print(df.shape)

"""Now we will clean the data, convert the date column, and downsample it to hourly values.

## Cleaning and Preparing Data

We convert the time column, sort the data and keep only the features needed for forecasting.
"""

df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d.%m.%Y %H:%M:%S")

df = df.sort_values("Date Time").reset_index(drop=True)

df.head()

"""## Downsample to Hourly Data

The original dataset has 10-minute observations.
We average every 6 rows to create hourly observations.
"""

df_hourly = df.groupby(np.arange(len(df)) // 6).mean(numeric_only=True)
df_hourly.head()

"""## Selecting Features

We keep a small set of useful weather features for forecasting
"""

features = ["T (degC)", "p (mbar)", "rho (g/m**3)", "wv (m/s)", "wd (deg)"]
data = df_hourly[features].copy()

data.head()

"""## Handling Missing Values

We remove or fill missing values before creating training windows
"""

data = data.fillna(method="ffill").fillna(method="bfill")

"""## Normalizing the data  
We will scale the features so training becomes more stable
"""

data_mean = data.mean()
data_std = data.std()

data_scaled = (data - data_mean) / data_std
data_scaled.head()

"""## Creating Sequences

We use the previous 72 hours of weather data to predict the next 12 hours of temperature
"""

def create_sequences(data_array, input_len=72, output_len=12):
    X, y = [], []
    for i in range(len(data_array) - input_len - output_len):
        X.append(data_array[i:i+input_len])
        y.append(data_array[i+input_len:i+input_len+output_len, 0])
    return np.array(X), np.array(y)

data_array = data_scaled.values
X, y = create_sequences(data_array, input_len=72, output_len=12)

print(X.shape, y.shape)

"""## Train-Test Split

We split the time series into training and testing sets without shuffling.
"""

split_idx = int(len(X) * 0.8)

X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

"""## Converting to Tensors

We convert the numpy arrays into PyTorch tensors for training.
"""

X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

"""## Creating DataLoaders

i prepare mini-batches for efficient training.
"""

train_dataset = TensorDataset(X_train, y_train)
test_dataset = TensorDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

"""## Custom LSTM Cell

We now implement the LSTM cell manually.This includes the input gate, forget gate, output gate, candidate state, cell state update, and hidden state update.
"""

class CustomLSTMCell(nn.Module):
    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.hidden_size = hidden_size

        self.W_ih = nn.Linear(input_size, 4 * hidden_size)
        self.W_hh = nn.Linear(hidden_size, 4 * hidden_size)

    def forward(self, x, h_prev, c_prev):
        gates = self.W_ih(x) + self.W_hh(h_prev)
        i, f, o, g = torch.chunk(gates, 4, dim=1)

        i = torch.sigmoid(i)
        f = torch.sigmoid(f)
        o = torch.sigmoid(o)
        g = torch.tanh(g)

        c_next = f * c_prev + i * g
        h_next = o * torch.tanh(c_next)

        return h_next, c_next

"""## Custom LSTM Model

We build a simple LSTM model using the custom LSTM cell.
The final hidden state is used to predict the next 12 hours of temperature.
"""

class CustomLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers=1):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.cells = nn.ModuleList()
        for layer in range(num_layers):
            self.cells.append(
                CustomLSTMCell(input_size if layer == 0 else hidden_size, hidden_size)
            )

        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        batch_size, seq_len, _ = x.size()

        h = [torch.zeros(batch_size, self.hidden_size, device=x.device) for _ in range(self.num_layers)]
        c = [torch.zeros(batch_size, self.hidden_size, device=x.device) for _ in range(self.num_layers)]

        for t in range(seq_len):
            inp = x[:, t, :]
            for layer in range(self.num_layers):
                h[layer], c[layer] = self.cells[layer](inp, h[layer], c[layer])
                inp = h[layer]

        out = self.fc(h[-1])
        return out

"""## Model Setup

We define the model, loss function, and optimizer.
"""

input_size = X_train.shape[2]
hidden_size = 64
output_size = 12
num_layers = 1

model = CustomLSTM(input_size, hidden_size, output_size, num_layers=num_layers).to(device)

criterion = nn.HuberLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

"""## Training Loop

We train the custom LSTM and track the loss after each epoch.
"""

train_losses = []
test_losses = []

num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for X_batch, y_batch in train_loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        optimizer.zero_grad()
        preds = model(X_batch)
        loss = criterion(preds, y_batch)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)
    train_losses.append(train_loss)

    model.eval()
    test_running_loss = 0.0
    with torch.no_grad():
        for X_batch, y_batch in test_loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            preds = model(X_batch)
            loss = criterion(preds, y_batch)
            test_running_loss += loss.item()

    test_loss = test_running_loss / len(test_loader)
    test_losses.append(test_loss)

    print(f"Epoch {epoch+1}/{num_epochs} | Train Loss: {train_loss:.4f} | Test Loss: {test_loss:.4f}")

"""## Evaluation

We now compute Huber Loss, MAE, and MSE on the test set.
"""

model.eval()
all_preds = []
all_targets = []

with torch.no_grad():
    for X_batch, y_batch in test_loader:
        X_batch = X_batch.to(device)
        preds = model(X_batch).cpu().numpy()
        all_preds.append(preds)
        all_targets.append(y_batch.numpy())

all_preds = np.vstack(all_preds)
all_targets = np.vstack(all_targets)

huber = np.mean(np.where(
    np.abs(all_preds - all_targets) < 1,
    0.5 * (all_preds - all_targets) ** 2,
    np.abs(all_preds - all_targets) - 0.5
))
mae = mean_absolute_error(all_targets, all_preds)
mse = mean_squared_error(all_targets, all_preds)

print("Huber Loss:", huber)
print("MAE:", mae)
print("MSE:", mse)

"""## Prediction Plot

We plot the predicted temperature against the actual temperature for one test window.
"""

true_vals = all_targets[0]
pred_vals = all_preds[0]

plt.figure(figsize=(10, 5))
plt.plot(true_vals, label="Actual Temperature", marker="o")
plt.plot(pred_vals, label="Predicted Temperature", marker="x")
plt.xlabel("Forecast Hour")
plt.ylabel("Normalized Temperature")
plt.title("Predicted vs Actual Temperature")
plt.legend()
plt.grid(True)
plt.show()

"""## Saving Model Weights

We save the trained model for submission
"""

torch.save(model.state_dict(), "custom_lstm_level2.pth")
print("Model saved as custom_lstm_level2.pth")

"""## Conclusion

In this notebook, I implemented a custom LSTM manually for weather forecasting.The model was trained on hourly Jena Climate data and evaluated using Huber Loss, MAE, and MSE.
"""